

package(
    default_visibility = ["//src:__subpackages__"],
)

android_library(
    name = "sworlde",
    srcs = [
        "GameViewModel.kt",
        "MainActivity.kt,
    ],
    manifest = "AndroidManifest.xml",
    resource_files = glob(["res/**"]),
)